/**
*Author: Joshua Bäuml
*/
@startuml

node "Application Server" <<device>>{
    node "Tomcat 8.4" <<JSP server>>{
        node Servlet <<execution Enviroment>>{
            artifact pom.xml
            artifact config.jsp
            artifact simulation.jsp
            artifact index.jsp
        }
    }
}
@enduml